export const T = {
  page: {
    minHeight: '100vh',
    background: '#fef9f0',
    fontFamily: "'Nunito', system-ui, sans-serif",
  },

  // Navbar
  navbar: {
    background: 'rgba(254,249,240,0.92)',
    backdropFilter: 'blur(16px)',
    WebkitBackdropFilter: 'blur(16px)',
    borderBottom: '1px solid #f3e8ff',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  navInner: {
    maxWidth: '1280px',
    margin: '0 auto',
    padding: '1rem 2.5rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  navBrand: { display: 'flex', alignItems: 'center', gap: '0.6rem' },
  navLogo: { fontSize: '1.6rem', lineHeight: 1 },
  navName: {
    fontWeight: '900',
    fontSize: '1.2rem',
    color: '#1e1333',
    letterSpacing: '-0.03em',
  },
  cartBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    borderRadius: '50px',
    padding: '0.65rem 1.25rem',
    cursor: 'pointer',
    minHeight: '46px',
    minWidth: '120px',
    fontFamily: 'inherit',
    transition: 'background 0.2s ease, box-shadow 0.2s ease',
  },
  cartBtnLabel: {
    fontWeight: '800',
    fontSize: '0.9rem',
    letterSpacing: '0.01em',
  },

  // Hero
  hero: {
    background: 'linear-gradient(160deg,#fef9f0 0%,#f3e8ff 55%,#fce7f3 100%)',
    padding: '5rem 0 4.5rem',
    position: 'relative',
    overflow: 'hidden',
    minHeight: '520px',
    display: 'flex',
    alignItems: 'center',
  },
  blob: {
    position: 'absolute',
    borderRadius: '50%',
    opacity: 0.7,
    pointerEvents: 'none',
  },
  heroContent: {
    maxWidth: '680px',
    margin: '0 auto',
    width: '100%',
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '1.5rem',
  },
  heroEyebrow: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.5rem',
    fontSize: '0.75rem',
    fontWeight: '800',
    color: '#a855f7',
    textTransform: 'uppercase',
    letterSpacing: '0.15em',
  },
  heroEyebrowDot: {
    width: '8px', height: '8px',
    borderRadius: '50%',
    background: '#a855f7',
    display: 'inline-block',
    boxShadow: '0 0 8px #a855f7',
  },
  heroTitle: {
    fontFamily: 'Georgia, "Times New Roman", serif',
    fontWeight: '900',
    color: '#1e1333',
    lineHeight: 1.05,
    letterSpacing: '-0.04em',
    margin: 0,
  },
  heroTitleAccent: {
    background: 'linear-gradient(135deg,#a855f7,#e879f9)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  heroSub: {
    color: '#7c6a9e',
    fontWeight: '600',
    lineHeight: 1.65,
    margin: 0,
  },
  heroCta: {
    padding: '0.9rem 2rem',
    borderRadius: '50px',
    border: 'none',
    background: 'linear-gradient(135deg,#a855f7,#e879f9)',
    color: 'white',
    fontWeight: '900',
    fontSize: '1rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
    boxShadow: '0 8px 28px rgba(168,85,247,0.4)',
    letterSpacing: '0.01em',
  },
  heroCtaSecundario: {
    padding: '0.9rem 1.75rem',
    borderRadius: '50px',
    border: '2px solid #e9d5ff',
    background: 'white',
    color: '#7c3aed',
    fontWeight: '900',
    fontSize: '1rem',
    cursor: 'pointer',
    fontFamily: 'inherit',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    letterSpacing: '0.01em',
  },
  heroCartCount: {
    background: '#a855f7',
    color: 'white',
    borderRadius: '50%',
    width: '22px', height: '22px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.7rem',
    fontWeight: '900',
    flexShrink: 0,
  },
  heroStats: {
    display: 'flex',
    paddingTop: '0.5rem',
    borderTop: '1px solid #e9d5ff',
  },
  heroStat: { display: 'flex', alignItems: 'center', gap: '0.5rem' },
  heroStatVal: { fontWeight: '900', fontSize: '1.1rem', color: '#1e1333', letterSpacing: '-0.03em' },
  heroStatLbl: { fontSize: '0.82rem', color: '#7c6a9e', fontWeight: '600' },

  // Sección productos
  productosBg: {
    background: '#ffffff',
    borderTop: '3px solid #f3e8ff',
    boxShadow: 'inset 0 6px 32px rgba(168,85,247,0.05)',
    width: '100%',
  },
  container: { maxWidth: '1280px', margin: '0 auto', width: '100%' },
  sectionHeader: { paddingTop: '3rem', paddingBottom: '2rem' },
  sectionTitle: {
    fontSize: 'clamp(1.6rem,4vw,2.2rem)',
    fontWeight: '900',
    color: '#1e1333',
    letterSpacing: '-0.04em',
    fontFamily: 'Georgia, serif',
    margin: 0,
  },
  sectionSub: {
    color: '#7c6a9e',
    fontWeight: '600',
    fontSize: '0.95rem',
    marginTop: '0.4rem',
  },

  // Filtros
  pill: {
    display: 'inline-flex', alignItems: 'center', gap: '0.4rem',
    padding: '0.55rem 1.1rem', borderRadius: '50px',
    border: '1.5px solid #e9d5ff', background: 'white', color: '#6d28d9',
    fontWeight: '700', fontSize: '0.87rem', cursor: 'pointer',
    transition: 'all 0.2s ease', whiteSpace: 'nowrap', minHeight: '44px',
    fontFamily: 'inherit', boxShadow: '0 1px 4px rgba(192,132,252,0.08)',
  },
  pillHover: {
    borderColor: '#c084fc', background: '#faf5ff',
    boxShadow: '0 4px 14px rgba(192,132,252,0.2)', transform: 'translateY(-2px)',
  },
  pillActive: {
    background: 'linear-gradient(135deg,#c084fc,#e879f9)',
    color: 'white', border: '1.5px solid transparent', fontWeight: '800',
    boxShadow: '0 6px 20px rgba(192,132,252,0.45)', transform: 'translateY(-1px)',
  },

  // Separador
  sep: { display: 'flex', alignItems: 'center', gap: '0.75rem', margin: '0 0 1.75rem' },
  sepLine: { flex: 1, height: '1px', display: 'block', background: 'linear-gradient(90deg,transparent,#e9d5ff,transparent)' },
  sepChip: {
    fontSize: '0.65rem', fontWeight: '900', color: '#a78bfa',
    textTransform: 'uppercase', letterSpacing: '0.1em', whiteSpace: 'nowrap',
    background: '#f3e8ff', padding: '0.25rem 0.8rem', borderRadius: '50px',
    border: '1px solid #e9d5ff',
  },
};
