const S = {
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(30,19,51,0.45)',
    backdropFilter: 'blur(4px)',
    WebkitBackdropFilter: 'blur(4px)',
    zIndex: 900,
  },
  panel: {
    position: 'fixed',
    top: 0,
    right: 0,
    bottom: 0,
    width: 'min(420px, 100vw)',
    background: '#fef9f0',
    zIndex: 901,
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '-16px 0 64px rgba(168,85,247,0.18)',
    fontFamily: "'Nunito', system-ui, sans-serif",
    overflowY: 'auto',
    scrollbarWidth: 'none',
  },
  panelHeader: {
    background: 'linear-gradient(130deg, #7c3aed 0%, #a855f7 55%, #e879f9 100%)',
    padding: '1.5rem 1.75rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexShrink: 0,
  },
  panelHeaderLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.875rem',
  },
  panelIcon: { fontSize: '2rem', lineHeight: 1 },
  panelTitle: {
    color: 'white',
    fontWeight: '900',
    fontSize: '1.15rem',
    letterSpacing: '-0.02em',
  },
  panelSub: {
    color: 'rgba(255,255,255,0.75)',
    fontSize: '0.78rem',
    fontWeight: '600',
    marginTop: '2px',
  },
  closeBtn: {
    background: 'rgba(255,255,255,0.18)',
    border: '1.5px solid rgba(255,255,255,0.3)',
    borderRadius: '50%',
    width: '38px',
    height: '38px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    color: 'white',
    fontSize: '0.85rem',
    fontWeight: '700',
    transition: 'background 0.2s ease',
    fontFamily: 'inherit',
    flexShrink: 0,
  },
  items: {
    flex: 1,
    padding: '0 1.5rem',
  },
  item: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingBlock: '1rem',
    borderBottom: '1px solid #f3e8ff',
    gap: '0.5rem',
    overflow: 'hidden',
  },
  itemLeft: { flex: 1, minWidth: 0, paddingRight: '0.5rem' },
  itemNombre: {
    fontSize: '0.9rem',
    fontWeight: '800',
    color: '#1e1333',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  itemUnit: {
    fontSize: '0.72rem',
    color: '#a78bfa',
    marginTop: '3px',
    fontWeight: '600',
  },
  itemRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    flexShrink: 0,
  },
  qtyControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.2rem',
    background: '#f3e8ff',
    borderRadius: '50px',
    padding: '3px',
    border: '1px solid #e9d5ff',
  },
  qtyBtn: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    border: 'none',
    cursor: 'pointer',
    fontWeight: '900',
    fontSize: '1rem',
    color: '#7c3aed',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'background 0.15s ease',
    lineHeight: 1,
    flexShrink: 0,
    fontFamily: 'inherit',
  },
  qtyNum: {
    minWidth: '24px',
    textAlign: 'center',
    fontWeight: '900',
    fontSize: '0.9rem',
    color: '#1e1333',
  },
  itemSubtotal: {
    fontSize: '0.92rem',
    fontWeight: '900',
    color: '#7c3aed',
    minWidth: '62px',
    textAlign: 'right',
    letterSpacing: '-0.01em',
  },
  removeBtn: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.72rem',
    padding: '4px',
    transition: 'color 0.15s ease',
    lineHeight: 1,
    flexShrink: 0,
    fontFamily: 'inherit',
  },
  totalArea: {
    padding: '1.25rem 1.75rem',
    background: '#f3e8ff',
    borderTop: '1px solid #e9d5ff',
    display: 'flex',
    flexDirection: 'column',
    gap: '0.6rem',
    flexShrink: 0,
  },
  shippingRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  shippingLabel: { fontSize: '0.8rem', color: '#7c6a9e', fontWeight: '600' },
  shippingFree: {
    fontSize: '0.7rem',
    fontWeight: '900',
    color: '#10b981',
    background: '#f0fdf4',
    padding: '0.22rem 0.7rem',
    borderRadius: '50px',
    border: '1px solid #bbf7d0',
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },
  totalRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  totalLabel: {
    fontSize: '0.75rem',
    fontWeight: '800',
    color: '#7c3aed',
    textTransform: 'uppercase',
    letterSpacing: '0.1em',
  },
  totalValue: {
    fontSize: '1.75rem',
    fontWeight: '900',
    color: '#1e1333',
    letterSpacing: '-0.04em',
    fontFamily: 'Georgia, serif',
  },
  ctaArea: {
    padding: '1.25rem 1.75rem 2rem',
    flexShrink: 0,
  },
  btnConfirmar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.65rem',
    width: '100%',
    background: 'linear-gradient(135deg, #7c3aed 0%, #a855f7 50%, #e879f9 100%)',
    color: 'white',
    border: 'none',
    padding: '1.15rem 1.5rem',
    borderRadius: '18px',
    fontSize: '1.05rem',
    fontWeight: '900',
    cursor: 'pointer',
    fontFamily: "'Nunito', inherit",
    letterSpacing: '0.01em',
    boxShadow: '0 8px 28px rgba(168,85,247,0.42)',
    height: 'auto',
  },
  empty: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem 1.5rem',
    textAlign: 'center',
    gap: '0.75rem',
  },
  emptyIcon: { fontSize: '3.5rem', opacity: 0.3, lineHeight: 1 },
  emptyTitle: { fontWeight: '900', color: '#1e1333', fontSize: '1.1rem', letterSpacing: '-0.02em' },
  emptySub: { color: '#a78bfa', fontSize: '0.85rem', fontWeight: '600', lineHeight: 1.5 },
};

export default S;
